spring.application.name=agro-web
spring.application.name=agro-web
server.port=8081

spring.datasource.url=jdbc:mariadb://127.0.0.1:3306/agro_iot
spring.datasource.username=root
spring.datasource.password=pucmm
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

spring.thymeleaf.cache=false
# Directorio externo para archivos servidos bajo /uploads/**
app.uploads.directorio=${AGRO_UPLOADS_DIRECTORY:uploads}